# Generated by Django 4.1.2 on 2022-11-13 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_issue_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("user", "project")},
        ),
    ]
